
	xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:ns="ns"
	xmlns:nscore="urn:core_{{nsVersion}}.platform.webservices.netsuite.com"
	xmlns:nscommon="urn:common_{{nsVersion}}.platform.webservices.netsuite.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:nsmessages="urn:messages_{{nsVersion}}.platform.webservices.netsuite.com"
	xmlns:nsrelationships="urn:relationships_{{nsVersion}}.lists.webservices.netsuite.com"
	xmlns:nsfilecabinet="urn:filecabinet_{{nsVersion}}.documents.webservices.netsuite.com"
	xmlns:nsaccounting="urn:accounting_{{nsVersion}}.lists.webservices.netsuite.com"
	xmlns:nstransactions="urn:sales_{{nsVersion}}.transactions.webservices.netsuite.com"
	xmlns:nscustomers="urn:customers_{{nsVersion}}.transactions.webservices.netsuite.com"
	xmlns:nsmarketing="urn:marketing_{{nsVersion}}.lists.webservices.netsuite.com"
	xmlns:nscustomization="urn:customization_{{nsVersion}}.setup.webservices.netsuite.com"
